[package]
name = "metavm-zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
metavm-core = { workspace = true }
curve25519-dalek = { workspace = true }
rand = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
bls48581 = { workspace = true }
blst = { workspace = true }
ed448-bulletproofs = { workspace = true }
verenc = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
